import { CapsuleItem, Outfit } from '@/types/wardrobe';

export const OUTFITS: Outfit[] = [
  {
    id: 'weekend-gentleman',
    occasion: 'casual',
    seasons: ['spring', 'summer'],
    title: 'The Weekend Gentleman',
    subtitle: 'Effortless warmth-season ease',
    pieces: [
      { item: 'Oxford shirt', color: 'White', fabric: 'Cotton' },
      { item: 'Chinos', color: 'Navy', fabric: 'Cotton twill' },
      { item: 'Leather sneakers', color: 'White' },
      { item: 'No-show socks', color: 'White' },
    ],
    palette: ['#FFFFFF', '#1B2B4B', '#F5F5F5', '#D4C9B0'],
    stylingNote: 'Roll the sleeves twice, leave one button undone. Tuck in loosely at front only for a relaxed drape.',
    accentColor: '#4A7C59',
  },
  {
    id: 'country-weekend',
    occasion: 'casual',
    seasons: ['autumn', 'winter'],
    title: 'The Country Weekend',
    subtitle: 'Earthy confidence for cooler days',
    pieces: [
      { item: 'Harrington jacket', color: 'Forest green', fabric: 'Cotton' },
      { item: 'Roll-neck', color: 'Cream', fabric: 'Merino wool' },
      { item: 'Moleskin trousers', color: 'Dark brown' },
      { item: 'Derby boots', color: 'Tan', fabric: 'Leather' },
    ],
    palette: ['#2E5B3A', '#F5F0E5', '#3B2B1A', '#8B6344'],
    stylingNote: 'Earth tones signal an easy confidence that city colours rarely achieve. Let the boots be the focal point.',
    accentColor: '#4A7C59',
  },
  {
    id: 'savile-row-scholar',
    occasion: 'professional',
    seasons: ['autumn', 'winter'],
    title: 'The Savile Row Scholar',
    subtitle: 'Considered authority for the boardroom',
    pieces: [
      { item: 'Two-piece suit', color: 'Charcoal grey', fabric: 'Wool' },
      { item: 'Oxford shirt', color: 'Light blue', fabric: 'Cotton' },
      { item: 'Tie', color: 'Burgundy', fabric: 'Silk' },
      { item: 'Brogue Oxfords', color: 'Dark tan', fabric: 'Leather' },
    ],
    palette: ['#3C3C3C', '#8DB4D4', '#8B1A1A', '#5C3D1E'],
    stylingNote: 'The pocket square should complement, never match the tie. A fold of white linen is always correct.',
    accentColor: '#2B4A8B',
  },
  {
    id: 'creative-professional',
    occasion: 'professional',
    seasons: ['spring', 'summer'],
    title: 'The Creative Professional',
    subtitle: 'Warm-weather authority without the armour',
    pieces: [
      { item: 'Linen blazer (unstructured)', color: 'Navy', fabric: 'Linen' },
      { item: 'Fine-knit polo', color: 'White', fabric: 'Cotton' },
      { item: 'Chinos', color: 'Stone' },
      { item: 'Loafers', color: 'Tan', fabric: 'Suede' },
    ],
    palette: ['#1B2B4B', '#F5F5F5', '#C5B89A', '#8B7355'],
    stylingNote: 'Linen communicates confidence — it says you are distinguished enough not to care about creases.',
    accentColor: '#2B4A8B',
  },
  {
    id: 'intimate-dinner',
    occasion: 'date',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    title: 'The Intimate Dinner',
    subtitle: 'Effortlessly sharp, never trying',
    pieces: [
      { item: 'Slim blazer', color: 'Navy' },
      { item: 'T-shirt', color: 'White', fabric: 'Pima cotton' },
      { item: 'Jeans', color: 'Dark indigo', fabric: 'Selvedge denim' },
      { item: 'Chelsea boots', color: 'Dark brown', fabric: 'Leather' },
    ],
    palette: ['#1B2B4B', '#FFFFFF', '#1A1A35', '#2C1A10'],
    stylingNote: 'Overly formal signals insecurity. Keep it effortlessly sharp — the goal is looking like you dressed this way without thinking.',
    accentColor: '#8B1A4A',
  },
  {
    id: 'black-tie',
    occasion: 'formal',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    title: 'Black Tie',
    subtitle: 'The uniform of civilised evenings',
    pieces: [
      { item: 'Dinner jacket', color: 'Black', fabric: 'Wool-silk' },
      { item: 'Dress shirt (pleated bib)', color: 'White', fabric: 'Cotton poplin' },
      { item: 'Bow tie', color: 'Black', fabric: 'Silk' },
      { item: 'Patent Oxfords', color: 'Black', fabric: 'Patent leather' },
    ],
    palette: ['#0A0A0A', '#F5F5F0', '#1C1C1C'],
    stylingNote: 'A perfect black tie look is invisible — it disappears so you become the focal point. Any deviation should be deliberate, not accidental.',
    accentColor: '#0A0A0A',
  },
  {
    id: 'sunday-morning',
    occasion: 'casual',
    seasons: ['spring', 'summer'],
    title: 'Sunday Morning',
    subtitle: 'Intentional leisure',
    pieces: [
      { item: 'Linen shirt (relaxed)', color: 'White', fabric: 'Linen' },
      { item: 'Tailored shorts', color: 'Slate grey', fabric: 'Cotton' },
      { item: 'Leather trainers', color: 'White' },
    ],
    palette: ['#F5F5F0', '#6B7280', '#F0F0F0'],
    stylingNote: 'Even in leisure, the cut should be deliberate. Baggy and shapeless communicates indifference, not ease.',
    accentColor: '#4A7C59',
  },
  {
    id: 'sharp-athlete',
    occasion: 'athletic',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    title: 'The Sharp Athlete',
    subtitle: 'Performance with presence',
    pieces: [
      { item: 'Technical tee (fitted)', color: 'Dark grey', fabric: 'Merino wool blend' },
      { item: 'Performance shorts', color: 'Black', fabric: 'Stretch nylon' },
      { item: 'Training shoes', color: 'White/Grey' },
    ],
    palette: ['#3C3C3C', '#0A0A0A', '#F5F5F5'],
    stylingNote: 'Athletic wear is not a licence for shapelessness — fit matters in the gym. A merino tee never shows sweat and looks deliberate.',
    accentColor: '#5B4A2B',
  },
];

export const CAPSULE_ESSENTIALS: CapsuleItem[] = [
  {
    id: 'white-oxford',
    item: 'White Oxford shirt',
    why: 'The most versatile garment a man can own. Dresses up or down with equal ease.',
    category: 'top',
  },
  {
    id: 'navy-suit',
    item: 'Navy two-piece suit',
    why: 'The one suit you need. Appropriate for funerals, weddings, and board meetings alike.',
    category: 'layer',
  },
  {
    id: 'dark-jeans',
    item: 'Dark indigo jeans',
    why: 'Selvedge or Japanese denim. Dark enough to look sharp, casual enough for weekends.',
    category: 'bottom',
  },
  {
    id: 'chinos',
    item: 'Navy chinos',
    why: 'The bridge between casual and professional. Buy twice — one navy, one stone.',
    category: 'bottom',
  },
  {
    id: 'merino-roll',
    item: 'Cream merino roll-neck',
    why: 'Replaces a shirt and tie in one movement. Instantly elevates a suit or stands alone.',
    category: 'top',
  },
  {
    id: 'navy-blazer',
    item: 'Single-breasted navy blazer',
    why: 'The cornerstone of the capsule wardrobe. Pairs with everything. Buy the best you can afford.',
    category: 'layer',
  },
  {
    id: 'white-tee',
    item: 'White Pima cotton T-shirt',
    why: 'Under a blazer with dark jeans, it signals confident understated taste.',
    category: 'top',
  },
  {
    id: 'chelsea-boots',
    item: 'Chelsea boots (dark brown)',
    why: 'The most versatile boot. Correct with jeans, chinos, and suits. Polish monthly.',
    category: 'footwear',
  },
  {
    id: 'white-sneakers',
    item: 'White leather sneakers',
    why: 'One clean pair of leather-soled trainers. Clean them weekly.',
    category: 'footwear',
  },
  {
    id: 'leather-belt',
    item: 'Leather belt (dark brown)',
    why: 'Always match the belt to the shoes. One rule, followed consistently.',
    category: 'accessory',
  },
];

export const CATEGORY_ITEM_ICON: Record<CapsuleItem['category'], string> = {
  top: '○',
  bottom: '—',
  layer: '□',
  footwear: '◇',
  accessory: '·',
};
